// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC484Ltvb1UhiMZL2PxsdYwOvdMwm9l3dQ',
    appId: '1:418548095638:web:affe8a2cd1deab76f900b7',
    messagingSenderId: '418548095638',
    projectId: 'fit-app-9ba94',
    authDomain: 'fit-app-9ba94.firebaseapp.com',
    storageBucket: 'fit-app-9ba94.firebasestorage.app',
    measurementId: 'G-VXHXT6FXR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlx2X3kV6rrls88uT1mcS47-vWI9jfxI',
    appId: '1:418548095638:android:bf9efe5ba4118a27f900b7',
    messagingSenderId: '418548095638',
    projectId: 'fit-app-9ba94',
    storageBucket: 'fit-app-9ba94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkT5xyh_CjSwzVNeg4dXJ0RorKrrY3ps',
    appId: '1:418548095638:ios:e73332d07b620d32f900b7',
    messagingSenderId: '418548095638',
    projectId: 'fit-app-9ba94',
    storageBucket: 'fit-app-9ba94.firebasestorage.app',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkT5xyh_CjSwzVNeg4dXJ0RorKrrY3ps',
    appId: '1:418548095638:ios:e73332d07b620d32f900b7',
    messagingSenderId: '418548095638',
    projectId: 'fit-app-9ba94',
    storageBucket: 'fit-app-9ba94.firebasestorage.app',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC484Ltvb1UhiMZL2PxsdYwOvdMwm9l3dQ',
    appId: '1:418548095638:web:613b0e528dd7c878f900b7',
    messagingSenderId: '418548095638',
    projectId: 'fit-app-9ba94',
    authDomain: 'fit-app-9ba94.firebaseapp.com',
    storageBucket: 'fit-app-9ba94.firebasestorage.app',
    measurementId: 'G-36D2C3Y7TW',
  );
}
